[package]
name = "glgame"
version = "0.1.0"
authors = ["MrWindwaker <lagr45@gmai.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5.1"
rand = "0.7.3"